trigger:
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    testRunTitle: 'Test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/ThatBlokeCalledJay.MediatR.Abstractions.csproj'
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PackageVersion'
